version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "toooo"
      POSTGRES_PASSWORD: "goooo"
      POSTGRES_DB: "cooool"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5454:5432" #Change 5432 to 5454 (don't forget rename in DBProtocol too, later if you wanna put 5432)

  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"